# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

In [90]:
import requests
from PIL import Image
import numpy as np
from io import BytesIO
import requests as rq
import pandas as pd

## ۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
nums_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
nums_array[nums_array % 2 != 0] = -1
nums_array


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## ۲-
 خروجی کد بالا را به شکل زیر تغییر دهید

In [15]:
nums_array[nums_array != -1] = np.sort(nums_array[nums_array != -1])
nums_array.reshape(2, 5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

## 3- 
[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [28]:
a1, a2 = np.array([1,2,3,2,3,4,3,4,5,6]), np.array([7,2,10,2,7,4,9,4,9,8])
comparison_result = a1 == a2
np.where(comparison_result)

(array([1, 3, 5, 7]),)

## 4-
array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [26]:
large_array = np.arange(15)
np.set_printoptions(threshold=np.inf)
large_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
np.any(np.isnan(large_array))

False

## ۵-
 مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [31]:
arr = np.array([1,2,3,2,3,4,3,4,5,6])
unique_values, counts = np.unique(arr, return_counts=True)
unique_values, counts

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1]))

## ۶-
 یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [41]:
random_arr = np.random.randint(1, 50, 30)
random_arr


array([39, 22,  3, 12, 28, 43, 49, 49, 32,  8, 34, 29,  2,  3,  4, 37,  7,
        2, 16, 33, 17, 43, 15, 41,  9, 15, 46, 15, 30, 28])

In [42]:
np.clip(random_arr, 10, 30)

array([30, 22, 10, 12, 28, 30, 30, 30, 30, 10, 30, 29, 10, 10, 10, 30, 10,
       10, 16, 30, 17, 30, 15, 30, 10, 15, 30, 15, 30, 28])

## ۷-
  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [70]:
arr_3d = np.arange(12).reshape(3, 1, 4)
arr_3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## ۸-
 بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [71]:
import numpy as np

np.random.seed(100)
a = np.random.randint(1,10, [8,4])
a

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5],
       [2, 6, 4, 5],
       [5, 4, 8, 2],
       [2, 8, 8, 1]])

In [77]:
max_in_each_row = np.max(a, axis=1)
max_in_each_column = np.max(a, axis=0)

max_in_each_row, max_in_each_column


(array([9, 8, 6, 9, 7, 6, 8, 8]), array([9, 9, 9, 8]))

## ۹-
 نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [83]:
start_date = pd.to_datetime('2022-02-01')
end_date = pd.to_datetime('2022-02-25')

all_dates = np.arange(start_date, end_date + pd.DateOffset(1), dtype='datetime64[D]')
all_dates


array(['2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04',
       '2022-02-05', '2022-02-06', '2022-02-07', '2022-02-08',
       '2022-02-09', '2022-02-10', '2022-02-11', '2022-02-12',
       '2022-02-13', '2022-02-14', '2022-02-15', '2022-02-16',
       '2022-02-17', '2022-02-18', '2022-02-19', '2022-02-20',
       '2022-02-21', '2022-02-22', '2022-02-23', '2022-02-24',
       '2022-02-25'], dtype='datetime64[D]')

## ۱۰-
 عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


In [96]:
res = rq.get("https://jpeg.org/images/jpeg-home.jpg")
image = Image.open(BytesIO(res.content))
image = image.resize((250, 250))
image_array = np.array(image)
image_array

array([[[143, 147, 174],
        [143, 147, 174],
        [145, 149, 176],
        [146, 150, 177],
        [146, 150, 177],
        [146, 150, 177],
        [149, 153, 180],
        [147, 151, 179],
        [145, 149, 178],
        [143, 148, 177],
        [139, 150, 176],
        [140, 152, 178],
        [142, 152, 181],
        [142, 151, 182],
        [143, 151, 182],
        [149, 155, 184],
        [151, 156, 185],
        [150, 155, 184],
        [148, 153, 182],
        [148, 153, 182],
        [151, 156, 185],
        [153, 157, 186],
        [151, 158, 188],
        [148, 157, 188],
        [148, 157, 188],
        [153, 158, 187],
        [154, 159, 188],
        [155, 160, 189],
        [156, 161, 190],
        [155, 160, 189],
        [155, 161, 187],
        [155, 161, 187],
        [155, 160, 188],
        [155, 160, 189],
        [155, 160, 189],
        [155, 160, 189],
        [155, 160, 189],
        [155, 160, 189],
        [156, 161, 190],
        [156, 161, 190],


# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

4-چیست bios کار

5- منظور از ~ چیست

- 1 - GRUB - /etc/default/grub
- 2 - /etc/myapp/config.yaml
- 3 - /dev/
- 4 - مسئول بارگذاری و اجرای سیستم‌عامل از روی رم
- 5 - home directory