# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

In [1]:
import numpy as np

## Question1

اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.where(arr % 2 == 1, -1, arr)
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Question2

خروجی کد بالا را به شکل زیر تغییر دهید

In [3]:
arr.reshape(2, 5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

## Question3

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [4]:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
condition = np.where(arr1 == arr2)
# values = arr1[condition]
# indices = condition
# print(f"values: {values}")
# print(f"indices: {indices}")

condition

(array([1, 3, 5, 7]),)

## Question4

array([ 0,  1,  2, ..., 12, 13, 14]

برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [5]:
arr = np.array([ 0, 1, 2, ..., 12, 13, 14])
arr = np.delete(arr, np.where(arr == Ellipsis))
arr

array([0, 1, 2, 12, 13, 14], dtype=object)

In [6]:
arr = arr.astype("float")
arr[[1, 4]] = np.nan
np.isnan(arr).any()

True

## Question5

مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [7]:
arr = np.array([1,2,3,2,3,4,3,4,5,6])

In [8]:
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1]))

## Question6

یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [9]:
random_numbers = np.random.uniform(1, 50, 30)
print(random_numbers)
random_numbers[random_numbers >  30] = 30
print(random_numbers)

[34.64480945 18.308757   36.32482608 18.76974291 26.08106582 29.57192439
 24.02324841 37.37385078 37.9495969  44.29282868 46.9321701  30.11299904
 43.00930534 20.06639432 15.67404869 48.42422978 40.84667164 23.72438219
 21.58399093  2.9624381  17.09123382 31.04951228 16.21124365 39.44941185
  7.73477159 39.36908705  9.62400129 46.28260725  6.56392179 11.28029695]
[30.         18.308757   30.         18.76974291 26.08106582 29.57192439
 24.02324841 30.         30.         30.         30.         30.
 30.         20.06639432 15.67404869 30.         30.         23.72438219
 21.58399093  2.9624381  17.09123382 30.         16.21124365 30.
  7.73477159 30.          9.62400129 30.          6.56392179 11.28029695]


## Question7

array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [10]:
arr1 = np.array([0, 1, 2])
arr2 = np.array([2, 3, 4, 5, 6])
arr3 = np.array([7, 8, 9])
array_of_arrays = np.array([arr1, arr2, arr3], dtype=object)
print(f"array_of_arrays: {array_of_arrays}")
print(f"array_of_arrays: {array_of_arrays.shape}")
print(np.concatenate(array_of_arrays))

array_of_arrays: [array([0, 1, 2]) array([2, 3, 4, 5, 6]) array([7, 8, 9])]
array_of_arrays: (3,)
[0 1 2 2 3 4 5 6 7 8 9]


## Question8

بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [11]:
np.random.seed(100)
a = np.random.randint(1,10, [8,4])
print(a)


[[9 9 4 8]
 [8 1 5 3]
 [6 3 3 3]
 [2 1 9 5]
 [1 7 3 5]
 [2 6 4 5]
 [5 4 8 2]
 [2 8 8 1]]


In [12]:
a.max(axis=1)

array([9, 8, 6, 9, 7, 6, 8, 8])

In [13]:
a.max(axis=0)

array([9, 9, 9, 8])

## Question9

نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [14]:
a = np.arange("2022-02-01" , "2022-02-25", 2, dtype='datetime64[D]')
b = np.arange("2022-02-02" , "2022-02-23", 2, dtype='datetime64[D]')
print(a)
np.sort(np.concatenate([a, b]))

['2022-02-01' '2022-02-03' '2022-02-05' '2022-02-07' '2022-02-09'
 '2022-02-11' '2022-02-13' '2022-02-15' '2022-02-17' '2022-02-19'
 '2022-02-21' '2022-02-23']


array(['2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04',
       '2022-02-05', '2022-02-06', '2022-02-07', '2022-02-08',
       '2022-02-09', '2022-02-10', '2022-02-11', '2022-02-12',
       '2022-02-13', '2022-02-14', '2022-02-15', '2022-02-16',
       '2022-02-17', '2022-02-18', '2022-02-19', '2022-02-20',
       '2022-02-21', '2022-02-22', '2022-02-23'], dtype='datetime64[D]')

## Question10

عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


In [15]:
import requests
from PIL import Image
from io import BytesIO

In [16]:
image_url = "https://cdn.thewirecutter.com/wp-content/media/2022/10/laptopstopicpage-2048px-2102-2x1-1.jpg?auto=webp&quality=75&crop=2:1&width=980&dpr=2"
response = requests.get(image_url)

In [17]:
image = Image.open(BytesIO(response.content))

In [18]:
resized_image = image.resize((250, 250))

In [19]:
np.array(resized_image)

array([[[242, 190, 202],
        [242, 190, 202],
        [242, 190, 203],
        ...,
        [246, 208, 221],
        [246, 208, 221],
        [246, 208, 221]],

       [[242, 190, 202],
        [242, 190, 202],
        [242, 190, 203],
        ...,
        [246, 208, 221],
        [246, 208, 221],
        [246, 208, 221]],

       [[242, 190, 202],
        [242, 190, 202],
        [242, 190, 203],
        ...,
        [246, 208, 221],
        [246, 208, 221],
        [246, 208, 221]],

       ...,

       [[ 33,  32,  40],
        [ 33,  32,  39],
        [ 27,  26,  32],
        ...,
        [ 78,  98, 122],
        [ 78,  98, 122],
        [ 78,  98, 122]],

       [[ 33,  32,  40],
        [ 35,  34,  42],
        [ 27,  26,  32],
        ...,
        [ 78,  98, 122],
        [ 78,  98, 122],
        [ 78,  98, 122]],

       [[ 33,  32,  40],
        [ 29,  31,  38],
        [ 21,  20,  26],
        ...,
        [ 78,  98, 122],
        [ 79,  99, 123],
        [ 78,  98, 122]]

# linux

## Question1

برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

/etc/default/grub

## Question2

شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

/etc

## Question3

به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

/dev

## Question4

چیست bios کار

The job of the BIOS (Basic Input/Output System) is to initialize and control the hardware components of a computer during the boot process. The BIOS checks the hardware integrity and identifies the connected devices such as the CPU, memory, hard drives, and peripherals. It then loads the bootloader into the memory to start the operating system. The BIOS also provides a set of low-level functions and settings that can be accessed by the user or the operating system for configuring and managing the hardware.

## Question5

منظور از ~ چیست

The home directory of the current user