# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

In [1]:
import numpy as np

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
arr =  np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
q1 = np.where(arr % 2 == 1, -1, arr)
q1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [3]:
q2 = q1.reshape(2,5)
q2

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [4]:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
# arr1[np.in1d(arr1, arr2)]
np.intersect1d(arr1,arr2,return_indices=True)

(array([2, 4]), array([1, 5]), array([1, 5]))

array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [ ]:
np.isin()
# ارگومان اول چیزی که میخواهیم و ارگومان دوم ارای در خروجی بولین تایپ میگیریم

۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [12]:
my_arry = np.array([1,2,3,2,3,4,3,4,5,6])
unique, counts = np.unique(my_arry, return_counts=True)

dict(zip(unique, counts))


{1: 1, 2: 2, 3: 3, 4: 2, 5: 1, 6: 1}

۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [17]:
random_arr = np.random.randint(1,50,30)
random_arr = np.where( random_arr<10,10 ,random_arr )
np.where(random_arr>30 ,30 ,random_arr )

array([30, 30, 20, 13, 10, 10, 27, 29, 15, 29, 19, 30, 18, 30, 21, 17, 18,
       27, 24, 28, 11, 17, 30, 10, 30, 30, 26, 30, 30, 30])

۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [20]:
arr_3d = np.random.randint(1, 10, size=(2, 3, 4))
arr_3d.reshape(-1)

array([8, 1, 6, 7, 7, 2, 1, 6, 5, 7, 8, 8, 6, 5, 5, 7, 4, 9, 7, 5, 6, 7,
       5, 2])

۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [33]:
import numpy as np

np.random.seed(100)
a = np.random.randint(1,10, [8,4])
print(a)
max_in_cul = a.max(axis = 0)
max_in_row = a.max(axis = 1)


[[9 9 4 8]
 [8 1 5 3]
 [6 3 3 3]
 [2 1 9 5]
 [1 7 3 5]
 [2 6 4 5]
 [5 4 8 2]
 [2 8 8 1]]


۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [48]:
np.arange('2005-02', '2005-03', dtype='datetime64[2D]')

array(['2005-01-31', '2005-02-02', '2005-02-04', '2005-02-06',
       '2005-02-08', '2005-02-10', '2005-02-12', '2005-02-14',
       '2005-02-16', '2005-02-18', '2005-02-20', '2005-02-22',
       '2005-02-24', '2005-02-26'], dtype='datetime64[2D]')

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


array([[[100, 103, 112],
        [ 98, 101, 110],
        [ 97, 100, 109],
        ...,
        [120, 119, 124],
        [120, 119, 124],
        [114, 113, 118]],

       [[107, 110, 119],
        [106, 109, 118],
        [102, 105, 114],
        ...,
        [116, 115, 121],
        [117, 116, 121],
        [116, 115, 120]],

       [[108, 111, 120],
        [108, 111, 120],
        [101, 104, 113],
        ...,
        [106, 105, 111],
        [112, 111, 116],
        [116, 115, 120]],

       ...,

       [[ 64,  62,  73],
        [ 66,  64,  75],
        [ 67,  65,  76],
        ...,
        [240, 241, 238],
        [237, 238, 233],
        [237, 238, 233]],

       [[ 65,  63,  74],
        [ 66,  64,  75],
        [ 70,  68,  79],
        ...,
        [241, 241, 239],
        [240, 241, 236],
        [240, 241, 236]],

       [[ 73,  71,  82],
        [ 70,  68,  79],
        [ 72,  70,  81],
        ...,
        [239, 239, 238],
        [240, 240, 237],
        [240, 241, 236]]

# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

4-چیست bios کار

5- منظور از ~ چیست