# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

In [1]:
import pandas as pd
import numpy as np

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
arr= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_indices = arr % 2 != 0
arr[odd_indices] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [5]:
reshaped_arr = np.reshape(arr, (2, 5))
reshaped_arr

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

 [1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [10]:
arr1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
arr2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
matual_arr_index = np.where(arr1 == arr2)
matual_arr = arr2[matual_arr_index]

print("matual elements : ", matual_arr)
print("matual indexs of elements : ", matual_arr_index)

matual elements :  [2 2 4 4]
matual indexs of elements :  (array([1, 3, 5, 7]),)


array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [26]:
wierd_arr = np.array([0, 1, 2, ..., 12, 13, 14])

def is_numeric(x):
    return isinstance(x, (int, float, complex))

numeric_mask = np.vectorize(is_numeric)(wierd_arr)
filtered_arr = wierd_arr[numeric_mask]

print(filtered_arr)

[0 1 2 12 13 14]


In [20]:
has_none = np.any(wierd_arr == None)
if has_none:
    print("The array contains None values.")
else:
    print("The array does not contain None values.")

The array does not contain None values.


۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [36]:
arr3 = np.array([1,2,3,2,3,4,3,4,5,6])
unique_values, counts = np.unique(arr3, return_counts=True)
for value, count in zip(unique_values, counts):
    print(f"Value {value} is repeated {count} times.")

Value 1 is repeated 1 times.
Value 2 is repeated 2 times.
Value 3 is repeated 3 times.
Value 4 is repeated 2 times.
Value 5 is repeated 1 times.
Value 6 is repeated 1 times.


۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [45]:
arr4 = np.random.uniform(1, 50, 30)
con4 = np.where(arr4 < 10, 10, arr4)
con5 = np.where(con4 > 30, 30, con4)
con5

array([30.        , 30.        , 30.        , 14.63152156, 30.        ,
       30.        , 30.        , 28.28908591, 30.        , 10.        ,
       30.        , 30.        , 14.82607302, 14.06253774, 10.        ,
       10.05570795, 15.52662764, 30.        , 30.        , 10.97243609,
       10.96668164, 10.        , 30.        , 30.        , 10.        ,
       24.03926923, 10.        , 30.        , 30.        , 30.        ])

۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [50]:
arr5 = np.arange(1, 28)
arr6 = arr5.reshape((3, 3, 3))
arr6_1d = arr6.reshape(1, -1)

arr6_1d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]])

۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [52]:
np.random.seed(100)
a = np.random.randint(1,10, [8,4])

max_in_each_row = np.max(a, axis=1)
max_in_each_column = np.max(a, axis=0)

print("max in each row : ", max_in_each_row)
print("max in each column : ", max_in_each_column)

max in each row :  [9 8 6 9 7 6 8 8]
max in each column :  [9 9 9 8]


۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [53]:
start_date = '2022-02-01'
end_date = '2022-02-25'
date_range = pd.date_range(start=start_date, end=end_date)
date_array = np.array(date_range)
date_array

array(['2022-02-01T00:00:00.000000000', '2022-02-02T00:00:00.000000000',
       '2022-02-03T00:00:00.000000000', '2022-02-04T00:00:00.000000000',
       '2022-02-05T00:00:00.000000000', '2022-02-06T00:00:00.000000000',
       '2022-02-07T00:00:00.000000000', '2022-02-08T00:00:00.000000000',
       '2022-02-09T00:00:00.000000000', '2022-02-10T00:00:00.000000000',
       '2022-02-11T00:00:00.000000000', '2022-02-12T00:00:00.000000000',
       '2022-02-13T00:00:00.000000000', '2022-02-14T00:00:00.000000000',
       '2022-02-15T00:00:00.000000000', '2022-02-16T00:00:00.000000000',
       '2022-02-17T00:00:00.000000000', '2022-02-18T00:00:00.000000000',
       '2022-02-19T00:00:00.000000000', '2022-02-20T00:00:00.000000000',
       '2022-02-21T00:00:00.000000000', '2022-02-22T00:00:00.000000000',
       '2022-02-23T00:00:00.000000000', '2022-02-24T00:00:00.000000000',
       '2022-02-25T00:00:00.000000000'], dtype='datetime64[ns]')

In [54]:
missing_dates = pd.date_range(start_date, end_date).difference(date_range)
date_array_with_missing = np.concatenate([date_array, missing_dates])
date_array_with_missing

array(['2022-02-01T00:00:00.000000000', '2022-02-02T00:00:00.000000000',
       '2022-02-03T00:00:00.000000000', '2022-02-04T00:00:00.000000000',
       '2022-02-05T00:00:00.000000000', '2022-02-06T00:00:00.000000000',
       '2022-02-07T00:00:00.000000000', '2022-02-08T00:00:00.000000000',
       '2022-02-09T00:00:00.000000000', '2022-02-10T00:00:00.000000000',
       '2022-02-11T00:00:00.000000000', '2022-02-12T00:00:00.000000000',
       '2022-02-13T00:00:00.000000000', '2022-02-14T00:00:00.000000000',
       '2022-02-15T00:00:00.000000000', '2022-02-16T00:00:00.000000000',
       '2022-02-17T00:00:00.000000000', '2022-02-18T00:00:00.000000000',
       '2022-02-19T00:00:00.000000000', '2022-02-20T00:00:00.000000000',
       '2022-02-21T00:00:00.000000000', '2022-02-22T00:00:00.000000000',
       '2022-02-23T00:00:00.000000000', '2022-02-24T00:00:00.000000000',
       '2022-02-25T00:00:00.000000000'], dtype='datetime64[ns]')

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


In [ ]:
#couldnt understand this

array([[[100, 103, 112],
        [ 98, 101, 110],
        [ 97, 100, 109],
        ...,
        [120, 119, 124],
        [120, 119, 124],
        [114, 113, 118]],

       [[107, 110, 119],
        [106, 109, 118],
        [102, 105, 114],
        ...,
        [116, 115, 121],
        [117, 116, 121],
        [116, 115, 120]],

       [[108, 111, 120],
        [108, 111, 120],
        [101, 104, 113],
        ...,
        [106, 105, 111],
        [112, 111, 116],
        [116, 115, 120]],

       ...,

       [[ 64,  62,  73],
        [ 66,  64,  75],
        [ 67,  65,  76],
        ...,
        [240, 241, 238],
        [237, 238, 233],
        [237, 238, 233]],

       [[ 65,  63,  74],
        [ 66,  64,  75],
        [ 70,  68,  79],
        ...,
        [241, 241, 239],
        [240, 241, 236],
        [240, 241, 236]],

       [[ 73,  71,  82],
        [ 70,  68,  79],
        [ 72,  70,  81],
        ...,
        [239, 239, 238],
        [240, 240, 237],
        [240, 241, 236]]

# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

4-چیست bios کار

5- منظور از ~ چیست

1. /etc/default/grub
2./etc or /etc/<app_name>
3./lib/modules/<kernel_version>
4.BIOS (Basic Input/Output System) is low-level software used in personal computers (PCs) and servers to perform basic hardware-related functions. It manages and communicates with the hardware components of the system, such as booting the operating system from a hard disk, system date and time settings, boot priority from storage devices, and similar settings.
5./home/<username>

!!! "I searched for all in linux questions" !!!
