# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.vectorize(lambda x:-1 if x%2!=0 else x)(arr)
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [ ]:
arr.reshape([2,5])

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [61]:
nparr1 = np.array([1,2,3,2,3,4,3,4,5,6])
nparr2 = np.array([[7,2,10,2,7,4,9,4,9,8]])
np.where(nparr1 == nparr2)[1]

(array([1, 3, 5, 7]),)

array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [ ]:
ar = np.array(np.random.randn(100000))
np.set_printoptions(threshold=np.inf)
ar

۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [14]:
np.unique(np.array([1,2,3,2,3,4,3,4,5,6]), return_counts=True)


(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1]))

۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [21]:
def func(x):
    if x<10:
        return 10
    elif x>30:
        return 30
    return x

ar6 = np.array(np.random.rand(30)*50)
ar6
q6_func = np.vectorize(func)
q6_func(ar6)

[33.14924709 30.39618519 25.54217583 19.57381963  4.24468725 35.04802683
  7.46221009  8.7607952  48.46878651 45.28799358 27.07073741 11.04564957
 19.78331448 45.29088422  7.17456182 26.43073495  5.63140353 18.6468186
 15.12981261 35.0725932  42.21729431 17.06519106 10.75266421 15.80499943
 31.49733997 32.77095484 31.90320938 29.84397576 19.11062236  9.63998387]
[30.         30.         25.54217583 19.57381963 10.         30.
 10.         10.         30.         30.         27.07073741 11.04564957
 19.78331448 30.         10.         26.43073495 10.         18.6468186
 15.12981261 30.         30.         17.06519106 10.75266421 15.80499943
 30.         30.         30.         29.84397576 19.11062236 10.        ]


۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [66]:
ar7 = np.array([[[1, 1, 1, 1], [2, 2, 2, 2]], [[12, 12, 12, 12], [13, 13, 13, 13]]])
ar7.flatten()

array_of_arrays:  [array([0, 1, 2]) array([2, 3, 4, 5, 6]) array([7, 8, 9])]
array_of_arrays:  (3,)
[0 1 2 2 3 4 5 6 7 8 9]


<ipython-input-66-a491e9c35e8a>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3])


۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [67]:
import numpy as np

np.random.seed(100)
a = np.random.randint(1,10, [8,4])
max_each_row = np.amax(a, axis=1)
max_each_col = np.amax(a, axis=0)
print(a)
print(max_each_row)
print(max_each_col)


[[9 9 4 8]
 [8 1 5 3]
 [6 3 3 3]
 [2 1 9 5]
 [1 7 3 5]
 [2 6 4 5]
 [5 4 8 2]
 [2 8 8 1]]


۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [58]:
ar = np.arange("2022-02-01", "2022-02-25", np.timedelta64(2, "D"), dtype="datetime64[D]")
ar
ar2 = np.arange("2022-02-02", "2022-02-25", np.timedelta64(2, "D"), dtype="datetime64[D]")
np.concatenate([ar, ar2])

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


In [60]:
import requests as rq

res = rq.get("https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/8b095976-57c2-42ac-a380-cbaaa936ee61/d816vrg-48400bea-09ba-40fc-b1b8-3af7651e1e8a.png/v1/fill/w_1024,h_576,q_80,strp/2014_08_27_15_21_58_by_catluvr2_d816vrg-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTc2IiwicGF0aCI6IlwvZlwvOGIwOTU5NzYtNTdjMi00MmFjLWEzODAtY2JhYWE5MzZlZTYxXC9kODE2dnJnLTQ4NDAwYmVhLTA5YmEtNDBmYy1iMWI4LTNhZjc2NTFlMWU4YS5wbmciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.UI6Vr5HyjPifhK5KkLPNKQW5_O-V75-X2LxJcV5sJ3g")
from io import BytesIO
from PIL import Image
img = BytesIO(res.content)
image = Image.open(img)
resized = image.resize((250, 250))
np.array(resized)


array([[[100, 103, 112],
        [ 98, 101, 110],
        [ 97, 100, 109],
        ...,
        [120, 119, 124],
        [120, 119, 124],
        [114, 113, 118]],

       [[107, 110, 119],
        [106, 109, 118],
        [102, 105, 114],
        ...,
        [116, 115, 121],
        [117, 116, 121],
        [116, 115, 120]],

       [[108, 111, 120],
        [108, 111, 120],
        [101, 104, 113],
        ...,
        [106, 105, 111],
        [112, 111, 116],
        [116, 115, 120]],

       ...,

       [[ 64,  62,  73],
        [ 66,  64,  75],
        [ 67,  65,  76],
        ...,
        [240, 241, 238],
        [237, 238, 233],
        [237, 238, 233]],

       [[ 65,  63,  74],
        [ 66,  64,  75],
        [ 70,  68,  79],
        ...,
        [241, 241, 239],
        [240, 241, 236],
        [240, 241, 236]],

       [[ 73,  71,  82],
        [ 70,  68,  79],
        [ 72,  70,  81],
        ...,
        [239, 239, 238],
        [240, 240, 237],
        [240, 241, 236]]

# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود
sudo nano /etc/default/grub


2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

json / yaml configuration file for changing configuration without changing the code

cofigparser



3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود
/dev/


4-چیست bios کار
پیکربندی سخت‌افزار
Power-On Self-Test (POST)
بارگذاری بوت‌لودر 
تنظیمات BIOS
اولین نرم‌افزاری است که در هنگام روشن کردن کامپیوتر اجرا می‌شود 


5- منظور از ~ چیست
تیلدا

مورد استفاده اصلی "~" در لینوکس و یونیکس اشاره به دایرکتوری خانه کاربری و ساخت مسیرهای نسبی در دستورات خط فرمان است.





