# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

In [1]:
import numpy as np

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

for index, value in enumerate(arr):
    if not (value % 2 == 0):
        arr[index] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [4]:
np.array([
    [ 0, -1,  2, -1,  4],
     [ -1,  6, -1,  8, -1]

])

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [12]:
arr0 = np.array([1,2,3,2,3,4,3,4,5,6])
arr1 = np.array([7,2,10,2,7,4,9,4,9,8])

common_indices_alt = np.where(arr1[:] == arr0)[0]

common_indices_alt

array([1, 3, 5, 7], dtype=int64)

array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [18]:
arr = np.array([ 0,  1,  2, ..., 12, 13, 14])
np.delete(arr,np.where(arr[:] == Ellipsis)[0][0])

array([0, 1, 2, 12, 13, 14], dtype=object)

۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [21]:
arr = np.array([1,2,3,2,3,4,3,4,5,6])

np.unique(arr, return_counts=True,)

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1], dtype=int64))

۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [30]:
arr = np.random.randint(1,50, 30)
for index , value in enumerate(arr):
    if value < 10:
        arr[index] = 10
    elif value < 30:
        arr[index] = 30

arr


array([42, 10, 36, 30, 31, 42, 48, 30, 34, 40, 44, 10, 10, 49, 49, 30, 30,
       45, 37, 37, 49, 30, 10, 30, 10, 10, 30, 10, 10, 30])

۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

array_of_arrays:  [array([0, 1, 2]) array([2, 3, 4, 5, 6]) array([7, 8, 9])]
array_of_arrays:  (3,)
[0 1 2 2 3 4 5 6 7 8 9]


<ipython-input-66-a491e9c35e8a>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3])


۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [44]:
import numpy as np

np.random.seed(100)
a = np.random.randint(1,10, [8,4])
print(a)

i

[[9 9 4 8]
 [8 1 5 3]
 [6 3 3 3]
 [2 1 9 5]
 [1 7 3 5]
 [2 6 4 5]
 [5 4 8 2]
 [2 8 8 1]]


array([[8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5],
       [2, 6, 4, 5],
       [5, 4, 8, 2],
       [2, 8, 8, 1]])

۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


numpy.datetime64('2020-02-12')

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


array([[[100, 103, 112],
        [ 98, 101, 110],
        [ 97, 100, 109],
        ...,
        [120, 119, 124],
        [120, 119, 124],
        [114, 113, 118]],

       [[107, 110, 119],
        [106, 109, 118],
        [102, 105, 114],
        ...,
        [116, 115, 121],
        [117, 116, 121],
        [116, 115, 120]],

       [[108, 111, 120],
        [108, 111, 120],
        [101, 104, 113],
        ...,
        [106, 105, 111],
        [112, 111, 116],
        [116, 115, 120]],

       ...,

       [[ 64,  62,  73],
        [ 66,  64,  75],
        [ 67,  65,  76],
        ...,
        [240, 241, 238],
        [237, 238, 233],
        [237, 238, 233]],

       [[ 65,  63,  74],
        [ 66,  64,  75],
        [ 70,  68,  79],
        ...,
        [241, 241, 239],
        [240, 241, 236],
        [240, 241, 236]],

       [[ 73,  71,  82],
        [ 70,  68,  79],
        [ 72,  70,  81],
        ...,
        [239, 239, 238],
        [240, 240, 237],
        [240, 241, 236]]

# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

4-چیست bios کار

5- منظور از ~ چیست