# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

In [2]:
import numpy as np

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
data_list=[0,1,2,3,4,5,6,7,8,9]
data_array=np.array(data_list)
data_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
data_array[data_array%2!=0]=-1
data_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [9]:
data_array.reshape(2,5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [16]:
list1 = [1,2,3,2,3,4,3,4,5,6]
list2 = [7,2,10,2,7,4,9,4,9,8]
arr1 = np.array(list1)
arr2 = np.array(list2)
intersect = np.intersect1d(arr1, arr2)
index1 = np.where(np.isin(arr1, intersect))[0]
index2 = np.where(np.isin(arr2, intersect))[0]
print(f'اعضای مشترک: {intersect}\n ایندکس های مشترک لیست اول: {index1}\n ایندکس های مشترک لیست دوم: {index2}')


اعضای مشترک: [2 4]
 ایندکس های مشترک لیست اول: [1 3 5 7]
 ایندکس های مشترک لیست دوم: [1 3 5 7]


array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [4]:
data_list = [1, 2, 3, 2, 3, 4, 3, 4, 5, 6]
data_array = np.array(data_list)
unique_values = np.unique(data_array)
count_of_each_value = np.bincount(data_array)
print(f"مقادیر یکتا:{unique_values}")
print(f"تعداد هر مقدار یکتا:{count_of_each_value[unique_values]}")


مقادیر یکتا:[1 2 3 4 5 6]
تعداد هر مقدار یکتا:[1 2 3 2 1 1]


۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [35]:
random_array = np.random.uniform(1, 51, 30)
print(random_array)
random_array[random_array < 10] = 10
random_array[random_array > 30] = 30
print(random_array)

[23.99213578  6.79434881  7.47161328  2.98369886 19.87547265 25.85227543
 16.53612713 35.22903138 26.27327078 13.42595758 41.00071741 44.88831928
 34.59393299 43.68760877 14.37645858 37.02308517  1.1040843   9.4327936
 27.05016625 22.96842904  9.46382979 14.04737656 12.60659551 25.44846811
 28.31007323  2.34536133 45.70135928 11.09954534  7.72578513 11.09657516]
[23.99213578 10.         10.         10.         19.87547265 25.85227543
 16.53612713 30.         26.27327078 13.42595758 30.         30.
 30.         30.         14.37645858 30.         10.         10.
 27.05016625 22.96842904 10.         14.04737656 12.60659551 25.44846811
 28.31007323 10.         30.         11.09954534 10.         11.09657516]


۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [46]:
arr = np.random.randint(1, 51, size=(3, 2, 5))
arr

array([[[11, 26, 21, 10, 17],
        [21, 21, 32, 26, 19]],

       [[47,  9,  4,  2,  3],
        [25, 45, 34, 18, 39]],

       [[15, 20, 15, 39, 44],
        [48, 17,  8, 14, 23]]])

In [48]:
arr.reshape(1,30)

array([[11, 26, 21, 10, 17, 21, 21, 32, 26, 19, 47,  9,  4,  2,  3, 25,
        45, 34, 18, 39, 15, 20, 15, 39, 44, 48, 17,  8, 14, 23]])

۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [50]:
np.random.seed(100)
a = np.random.randint(1,10, [8,4])
print(a)
max_row=np.max(a,axis=1)
max_col=np.max(a,axis=0)
print(f"بزرگترین هر ردیف:\n {max_row}")
print(f"بزرگترین هر ردیف:\n {max_col}")

[[9 9 4 8]
 [8 1 5 3]
 [6 3 3 3]
 [2 1 9 5]
 [1 7 3 5]
 [2 6 4 5]
 [5 4 8 2]
 [2 8 8 1]]
بزرگترین هر ردیف:
 [9 8 6 9 7 6 8 8]
بزرگترین هر ردیف:
 [9 9 9 8]


۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [9]:
dt=np.arange(np.datetime64('2022-02-01'), np.datetime64('2022-02-25'),np.timedelta64(2, "D"))
dt

array(['2022-02-01', '2022-02-03', '2022-02-05', '2022-02-07',
       '2022-02-09', '2022-02-11', '2022-02-13', '2022-02-15',
       '2022-02-17', '2022-02-19', '2022-02-21', '2022-02-23'],
      dtype='datetime64[D]')

In [10]:
extra = (dt[1] - dt[0])
result = np.arange(np.datetime64(dt[0]), np.datetime64(dt[-1] + extra))
result

array(['2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04',
       '2022-02-05', '2022-02-06', '2022-02-07', '2022-02-08',
       '2022-02-09', '2022-02-10', '2022-02-11', '2022-02-12',
       '2022-02-13', '2022-02-14', '2022-02-15', '2022-02-16',
       '2022-02-17', '2022-02-18', '2022-02-19', '2022-02-20',
       '2022-02-21', '2022-02-22', '2022-02-23', '2022-02-24'],
      dtype='datetime64[D]')

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


array([[[100, 103, 112],
        [ 98, 101, 110],
        [ 97, 100, 109],
        ...,
        [120, 119, 124],
        [120, 119, 124],
        [114, 113, 118]],

       [[107, 110, 119],
        [106, 109, 118],
        [102, 105, 114],
        ...,
        [116, 115, 121],
        [117, 116, 121],
        [116, 115, 120]],

       [[108, 111, 120],
        [108, 111, 120],
        [101, 104, 113],
        ...,
        [106, 105, 111],
        [112, 111, 116],
        [116, 115, 120]],

       ...,

       [[ 64,  62,  73],
        [ 66,  64,  75],
        [ 67,  65,  76],
        ...,
        [240, 241, 238],
        [237, 238, 233],
        [237, 238, 233]],

       [[ 65,  63,  74],
        [ 66,  64,  75],
        [ 70,  68,  79],
        ...,
        [241, 241, 239],
        [240, 241, 236],
        [240, 241, 236]],

       [[ 73,  71,  82],
        [ 70,  68,  79],
        [ 72,  70,  81],
        ...,
        [239, 239, 238],
        [240, 240, 237],
        [240, 241, 236]]

# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

4-چیست bios کار

5- منظور از ~ چیست