# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

In [1]:
import numpy as np

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
arr1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# np.where(arr1%2==0,1,arr1)
arr1[1::2]=1
arr1

array([0, 1, 2, 1, 4, 1, 6, 1, 8, 1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [16]:
arr1[1::2]=-1
np.reshape(arr1,(2,5))

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [237]:
list1=np.array([1,2,3,2,3,4,3,4,5,6])
list2=np.array([7,2,10,2,7,4,9,4,9,8])
print('list_of_index: ',np.where(list1==list2)[0],'\nlist_of_mutual:',list1[list1==list2])


list_of_index:  [1 3 5 7] 
list_of_mutual: [2 2 4 4]


In [39]:
# np.isnan(list1)
np.allclose(np.nan,list1)

False

array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


 ##### to print without elipsis:np.set_printoptions(threshold=len(arr))
 ##### to check each element is nan: np.isclose(np.nan,arr1)
 ##### to check is there any nan in array: np.allclose(np.nan,arr1)


۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [50]:
uniq_list=np.array([1,2,3,2,3,4,3,4,5,6])
unique,count=np.unique(uniq_list,return_counts=True)
print(f'The first item is unique value and second is count of it :{[*zip(unique , count)]}') 

The first item is unique value and second is count of it :[(1, 1), (2, 2), (3, 3), (4, 2), (5, 1), (6, 1)]


۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [62]:
arr3=np.random.randint(1,50,30)
# np.where(arr3<10,10,arr3>30,30)
def change_10_30(x):
    if x<10:
        return 10
    elif x>30:
        return 30
    else:
        return x
arr3

array([13, 13, 40, 34, 23, 44,  5, 44, 26, 14, 43, 28, 37, 25, 42, 26, 32,
        5,  7, 45, 49, 47, 13, 36, 12, 26, 14, 47, 26,  9])

In [63]:
change_array=np.vectorize(change_10_30)
change_array(arr3)

array([13, 13, 30, 30, 23, 30, 10, 30, 26, 14, 30, 28, 30, 25, 30, 26, 30,
       10, 10, 30, 30, 30, 13, 30, 12, 26, 14, 30, 26, 10])

۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [68]:
arr4=np.random.randint(1,100,[3,5,2])

In [69]:
arr4

array([[[82, 22],
        [45, 10],
        [25, 40],
        [89, 87],
        [80, 81]],

       [[68, 53],
        [54, 76],
        [71, 46],
        [30, 81],
        [26,  3]],

       [[74, 70],
        [33, 35],
        [83, 26],
        [23, 85],
        [89, 96]]])

In [75]:
arr4.flatten()

array([82, 22, 45, 10, 25, 40, 89, 87, 80, 81, 68, 53, 54, 76, 71, 46, 30,
       81, 26,  3, 74, 70, 33, 35, 83, 26, 23, 85, 89, 96])

۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [162]:
# import numpy as np

np.random.seed(100)
a = np.random.randint(1,10, [8,4])
print(a)


[[9 9 4 8]
 [8 1 5 3]
 [6 3 3 3]
 [2 1 9 5]
 [1 7 3 5]
 [2 6 4 5]
 [5 4 8 2]
 [2 8 8 1]]


In [163]:
print(f'maximum in each columns: {a.max(0)}, maximum in each row: {a.max(1)}')

maximum in each columns: [9 9 9 8], maximum in each row: [9 8 6 9 7 6 8 8]


۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید

In [86]:
from datetime import datetime ,timedelta 


In [146]:
date_1=np.arange(np.datetime64('2022-02-02'),np.datetime64('2022-02-25'),2)

In [158]:
date_2=np.arange(np.datetime64('2022-02-03'),np.datetime64('2022-02-25'),2)

In [159]:
date_1

array(['2022-02-02', '2022-02-04', '2022-02-06', '2022-02-08',
       '2022-02-10', '2022-02-12', '2022-02-14', '2022-02-16',
       '2022-02-18', '2022-02-20', '2022-02-22', '2022-02-24'],
      dtype='datetime64[D]')

In [157]:
np.sort(np.append(np.datetime_as_string(date_1),(np.datetime_as_string(date_2))))

array(['2022-02-02', '2022-02-03', '2022-02-04', '2022-02-05',
       '2022-02-06', '2022-02-07', '2022-02-08', '2022-02-09',
       '2022-02-10', '2022-02-11', '2022-02-12', '2022-02-13',
       '2022-02-14', '2022-02-15', '2022-02-16', '2022-02-17',
       '2022-02-18', '2022-02-19', '2022-02-20', '2022-02-21',
       '2022-02-22', '2022-02-23', '2022-02-24'], dtype='<U28')

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


In [175]:
import requests
from io import BytesIO
from PIL import Image

In [190]:
url='https://w0.peakpx.com/wallpaper/803/135/HD-wallpaper-dark-logo-dark-netflix-dark-season-dark-web-series-german-sci-fi-thriller.jpg'

In [191]:
response = requests.get(url)

In [192]:
BytesIO(response.content)

In [194]:
image=Image.open(BytesIO(response.content))


In [200]:
image.size

(800, 1422)

In [222]:
np_image=np.array(image)

In [229]:
resise_image=image.resize((250,250))

In [234]:
resise_image=np.array(resise_image)

In [235]:
resise_image.shape

(250, 250, 3)

# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

4-چیست bios کار

5- منظور از ~ چیست

# 1

   sudo nano /etc/default/grub

# 2


/etc or /etc/<module_name>. 
________Restarting Services: After modifying a configuration file, you may need to restart the corresponding service


# 3


/sys

# 4

BIOS stands for Basic Input/Output System. It is a firmware that is built into the computer's motherboard and is responsible for initializing and controlling the hardware components during the boot process.

# 5

In a Linux terminal, the tilde (~) is a shorthand notation that represents the current user's home directory.