In [1]:
import numpy as np

# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr_whered =np.where(arr%2==1 , -1    ,   arr   )
arr_whered

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [3]:
np.reshape(arr_whered,(2,5))

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [4]:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(arr1,arr2,return_indices=True)
# ===> index=1

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [5]:
import sys
np.set_printoptions(threshold=sys.maxsize) 

In [6]:

ar = np.array([1,2,3,4,None])
np.isin(None,ar)

array(True)

۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [7]:
arrrr = np.array([1,2,3,2,3,4,3,4,5,6])
arrrr_uniqued = np.unique(arrrr)
def f(lst:list):
    dict = {}
    for i in lst:
        if i in dict:
            dict[i] += 1
        else:
            dict[i] = 1
    return dict
f(arrrr)
        

{1: 1, 2: 2, 3: 3, 4: 2, 5: 1, 6: 1}

۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [8]:
rnd = np.random.randint(1,50,30)
np.where( rnd<10,10 ,rnd )
np.where(rnd>30 ,30 ,rnd )

array([ 3, 30, 16,  8,  7, 22, 28, 30, 29,  4, 30,  9,  6, 27, 30, 27, 30,
       30, 12, 15,  3,  8, 30, 17, 30, 30,  3, 30, 30, 30])

۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [9]:
rndn = np.random.randn(12)
rndn_reshaped= np.reshape(rndn , (2,2,3))
np.reshape(rndn_reshaped,12)

array([-0.75536118, -0.4660128 , -0.75257829,  0.75317363, -0.35879396,
       -0.27681914,  1.82397141,  1.68426214, -0.75736235,  0.07348366,
       -1.18780776,  0.58030129])

۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [10]:
import numpy as np
#هر ردیف
np.random.seed(100)
a = np.random.randint(1,10, [8,4])
soton=np.amax(a,axis=0)
radif=np.amax(a,axis=1)

۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [27]:
from datetime import *

TypeError: descriptor 'date' for 'datetime.datetime' objects doesn't apply to a 'int' object

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

etc/default/grub


2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند



3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود
tape drive




4-چیست bios کار
تنظیمات سخت افزاری و اجرای برنامه های اولیه سیستم عامل است 


5- منظور از ~ چیست


دایرکتوری خانه کاربری 