In [1]:
import numpy as np

### EX1

In [4]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1[arr1%2==1]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### EX2

In [6]:
arr2 = narray.reshape(2,5)

In [7]:
arr2

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

### EX3

In [8]:
narr1 = np.array([1,2,3,2,3,4,3,4,5,6])
narr2 = np.array([7,2,10,2,7,4,9,4,9,8])

### EX4

In [9]:
arr4 = np.arange(16)
np.set_printoptions(threshold=len(arr4))
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### EX5

In [10]:
arr5 = np.array([1,2,3,2,3,4,3,4,5,6])
np.unique(arr5,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1], dtype=int64))

### EX6

In [11]:
arr6 = np.random.randint(low=1, high=51, size=30)
arr6

array([13, 26, 25, ..., 25,  1, 41])

In [13]:
arr6[arr6<10]=10
arr6[arr6>30]=30
np.set_printoptions(threshold=len(arr6))
arr6

array([13, 26, 25, 22, 30, 27, 14, 26, 30, 10, 17, 20, 10, 16, 17, 30, 14,
       10, 22, 23, 27, 29, 29, 13, 30, 25, 30, 25, 10, 30])

### EX7

In [14]:
arr7 = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr7.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### EX8

In [18]:
np.random.seed(100)
arr8 = np.random.randint(1,10, [8,4])
arr8

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       ...,
       [2, 6, 4, 5],
       [5, 4, 8, 2],
       [2, 8, 8, 1]])

In [20]:
np.shape(arr8)

(8, 4)

In [21]:
np.min(arr8, axis=1)

array([4, 1, 3, 1, 1, 2, 2, 1])

In [22]:
np.max(arr8, axis=0)

array([9, 9, 9, 8])

### EX9

In [24]:
dstart = np.datetime64('2022-02-01')
dend = np.datetime64('2022-02-25')
arr9 = np.arange(dstart, dend, np.timedelta64(2,'D'))
arr9

array(['2022-02-01', '2022-02-03', '2022-02-05', '2022-02-07',
       '2022-02-09', '2022-02-11', '2022-02-13', '2022-02-15',
       '2022-02-17', '2022-02-19', '2022-02-21', '2022-02-23'],
      dtype='datetime64[D]')

## Linux

1. GRUB
2. 
3. etc
در این دایرکتوری فایل های کانفیگوریشن مربوط به سیستم عامل و سرویس ها وجود دارد  
4. 
وظیفه آن مدیریت سخت افزارهای دستگاه ها است برای اولین بار زمان روشن شدن دستگاه اجرا می شود و کنترل را به سیستم عامل میدهد
5. home directory