In [101]:
import numpy as np
import sys
import random
from datetime import datetime, timedelta

# Tamrin1

In [4]:
a = np.array([0, 1, 2, 3, 4, 5,6, 7, 8,9])
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Tamrin2

In [10]:
b = a.reshape(2, -1)
b

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

# Tamrin3

In [18]:
c1 = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
c2 = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9,8])

np.where(c1 == c2)

(array([1, 3, 5, 7], dtype=int64),)

# Tamrin4

In [66]:
d = np.array([1, 2, 3, ..., 15])
d = np.arange(15)
#np.set_printoptions(threshold=np.inf)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
def find_ellipsis(x):
    if len(np.arange(x[-1])) - len(x) > 0:
        print('There is Ellipsis in your numpy array')
    else:
        print('**')

find_ellipsis(np.array([1, 2, ... , 15]))

There is Ellipsis in your numpy array


# Tamrin5

In [69]:
e = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
unique, counts = np.unique(e, return_counts=True)
unique, counts

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 3, 2, 1, 1], dtype=int64))

# Tamrin6

In [81]:
rand_num = np.random.uniform(1, 50, size=(30,))
rand_num

array([33.68148155,  4.01815098, 43.50774547,  7.41390648, 48.27775945,
       22.86508626, 44.21434909,  9.06476149, 30.56724203, 12.43992188,
       24.50041327, 40.35493505, 33.90764865, 44.19808017, 16.35420525,
       33.60968532,  7.81373485, 46.34566223, 44.65724804, 24.01345937,
       28.12554611, 19.61787803, 33.82777439,  5.58194352, 17.37316552,
        9.83708586, 31.74331908, 20.08730524, 24.75378505, 13.42623811])

In [83]:
rand_num[rand_num < 10] = 10
rand_num[rand_num > 30] = 30
rand_num

array([30.        , 10.        , 30.        , 10.        , 30.        ,
       22.86508626, 30.        , 10.        , 30.        , 12.43992188,
       24.50041327, 30.        , 30.        , 30.        , 16.35420525,
       30.        , 10.        , 30.        , 30.        , 24.01345937,
       28.12554611, 19.61787803, 30.        , 10.        , 17.37316552,
       10.        , 30.        , 20.08730524, 24.75378505, 13.42623811])

# Tamrin7

In [85]:
array_of_arrays = np.array([[[0, 1, 2]],[[4, 5, 6]],[[7, 8, 9]]])
array_of_arrays

array([[[0, 1, 2]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [88]:
change_3d_array = np.reshape(array_of_arrays, (1, np.product(array_of_arrays.shape)))
change_3d_array

array([[0, 1, 2, 4, 5, 6, 7, 8, 9]])

# Tamrin8

In [91]:
np.random.seed(100)
f = np.random.randint(1,10, [8,4])
f

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5],
       [2, 6, 4, 5],
       [5, 4, 8, 2],
       [2, 8, 8, 1]])

In [94]:
max_row = np.max(f, axis = 1)
max_row

array([9, 8, 6, 9, 7, 6, 8, 8])

In [97]:
max_column = np.max(f, axis = 0)
max_column

array([9, 9, 9, 8])

# Tamrin9

In [131]:
arr1 = np.arange(np.datetime64("2018-02-01"), np.datetime64("2018-02-24"), np.timedelta64(2, 'D'))
arr1

array(['2018-02-01', '2018-02-03', '2018-02-05', '2018-02-07',
       '2018-02-09', '2018-02-11', '2018-02-13', '2018-02-15',
       '2018-02-17', '2018-02-19', '2018-02-21', '2018-02-23'],
      dtype='datetime64[D]')

In [136]:
arr2 = np.arange(np.datetime64("2018-02-02"), np.datetime64("2018-02-25"), np.timedelta64(2, 'D'))
arr2

array(['2018-02-02', '2018-02-04', '2018-02-06', '2018-02-08',
       '2018-02-10', '2018-02-12', '2018-02-14', '2018-02-16',
       '2018-02-18', '2018-02-20', '2018-02-22', '2018-02-24'],
      dtype='datetime64[D]')

In [137]:
con = np.stack((arr1, arr2), axis = 1)
con

array([['2018-02-01', '2018-02-02'],
       ['2018-02-03', '2018-02-04'],
       ['2018-02-05', '2018-02-06'],
       ['2018-02-07', '2018-02-08'],
       ['2018-02-09', '2018-02-10'],
       ['2018-02-11', '2018-02-12'],
       ['2018-02-13', '2018-02-14'],
       ['2018-02-15', '2018-02-16'],
       ['2018-02-17', '2018-02-18'],
       ['2018-02-19', '2018-02-20'],
       ['2018-02-21', '2018-02-22'],
       ['2018-02-23', '2018-02-24']], dtype='datetime64[D]')

In [138]:
change_con = np.reshape(con, (1, np.product(con.shape)))
change_con

array([['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
        '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
        '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
        '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
        '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
        '2018-02-21', '2018-02-22', '2018-02-23', '2018-02-24']],
      dtype='datetime64[D]')