In [53]:
import numpy as np

In [54]:
# Question 1:
my_np = np.arange(10)
my_np[my_np % 2 != 0]  = -1
my_np

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [55]:
# Question 2:
answer = my_np.reshape(2, 5)
answer

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [56]:
# Question 3:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
result1 = np.intersect1d(arr1, arr2)
result2 = np.where(arr1==arr2)
print ('Common elements are:', result1, 'and their indexes are:', result2)

Common elements are: [2 4] and their indexes are: (array([1, 3, 5, 7], dtype=int64),)


In [58]:
# Question 4:
# print numpy array without truncation
my_arr1 = np.arange(10000)
np.set_printoptions(threshold=np.inf)
# check numpy array is nan
my_arr2 = ([[1,2,3,4],
            [2,3,np.nan,5],
            [np.nan,5,2,3]])
np.isnan(my_arr2)

array([[False, False, False, False],
       [False, False,  True, False],
       [ True, False, False, False]])

In [60]:
# Question 5:
from collections import Counter
my_arr = np.array([1,2,3,2,3,4,3,4,5,6])
unique_values, counts = np.unique(my_arr, return_counts=True)
print ('unique values are:', unique_values, 'and counts of elements are:', counts)

unique values are: [1 2 3 4 5 6] and counts of elements are: [1 2 3 2 1 1]


In [61]:
# Question 6: 
rand_arr = np.random.randint(1, 50, 30)
np.select([rand_arr < 10, rand_arr > 30], [10, 30], rand_arr)

array([15, 20, 30, 30, 10, 10, 21, 19, 30, 28, 11, 10, 15, 30, 18, 10, 17,
       10, 30, 16, 30, 30, 30, 30, 30, 30, 30, 30, 26, 11])

In [62]:
# Question 7:
# create 3D numpy array
my_arr = np.array([0, 1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape((2, 2, 3))
#reshaping 3D to 1D
reshaped_my_arr = my_arr.reshape(12)
print ('reshaping 3D:', my_arr, '\n and reshaping 3D to 1D:', reshaped_my_arr)

reshaping 3D: [[[ 0  1  2]
  [ 2  3  4]]

 [[ 5  6  7]
  [ 8  9 10]]] 
 and reshaping 3D to 1D: [ 0  1  2  2  3  4  5  6  7  8  9 10]


In [63]:
# Question 8:
np.random.seed(100)
my_arr = np.random.randint(1, 10, [8,4])
max_each_col = np.max(my_arr, axis = 0)
max_each_row = np.max(my_arr, axis = 1)
print(' max each column is:', max_each_col, '\n max each row is:', max_each_row)

 max each column is: [9 9 9 8] 
 max each row is: [9 8 6 9 7 6 8 8]


In [50]:
# Question 9:
from datetime import datetime, timedelta
datetime_arr = np.arange(np.datetime64('2022-02-01'), np.datetime64('2022-02-25'), 2)
fn_arr = lambda x: x[:-2]+1
total_datetime_arr=np.sort(np.append(datetime_arr, fn_arr(datetime_arr)))
print('first datetime:\n', datetime_arr, '\nsecond datetime:\n', total_datetime_arr)

first datetime:
 ['2022-02-01' '2022-02-03' '2022-02-05' '2022-02-07' '2022-02-09'
 '2022-02-11' '2022-02-13' '2022-02-15' '2022-02-17' '2022-02-19'
 '2022-02-21' '2022-02-23'] 
second datetime:
 ['2022-02-01' '2022-02-02' '2022-02-03' '2022-02-04' '2022-02-05'
 '2022-02-06' '2022-02-07' '2022-02-08' '2022-02-09' '2022-02-10'
 '2022-02-11' '2022-02-12' '2022-02-13' '2022-02-14' '2022-02-15'
 '2022-02-16' '2022-02-17' '2022-02-18' '2022-02-19' '2022-02-20'
 '2022-02-21' '2022-02-23']


In [64]:
# Question 10:
import requests
from io import BytesIO
from PIL import Image
url = "https://dl.profilepic.ir/2019/06/Girl-Profile-01.jpg"
response = requests.get(url)
img = Image.open(BytesIO(response.content))
img = img.resize((250, 250))
img.show()

In [65]:
# Linux:
 # Q4
 #  بایوس از سیستم عامل مستقل است 
 # مهمترین کار بایوس راه اندازی سیستم عامل است. بایوس قطعات سیستم را تست کرده و ترتیب حافظه هایی که برای بوت شدن اولویت بندی شده اند را بررسی می کند و در نتیجه اگر مشکلی نبود سیستم عامل را راه اندازی می کند.
 # Q5
 # به عنوان دایرکتوری یک یوزر در نظر گرفته می شود