# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [2]:
cols_names=['class', 'Alcohol', 'Malicacid', 'Ash', 'Alcalinity_of_ash', 'Magnesium', 'Total_phenols', 'Flavanoids', 'Nonflavanoid_phenols', 'Proanthocyanins', 'Color_intensity', 'Hue', '0D280_0D315_of_diluted_wines', 'Proline']
wine_df = pd.read_csv('wine.data', names = cols_names)
wine_df.head(2)

class  Alcohol  Malicacid   Ash  Alcalinity_of_ash  Magnesium  \
0      1    14.23       1.71  2.43               15.6        127   
1      1    13.20       1.78  2.14               11.2        100   

   Total_phenols  Flavanoids  Nonflavanoid_phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   

   Color_intensity   Hue  0D280_0D315_of_diluted_wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050

# EDA

## Note: The EDA section was done in the previous homework.

# Split features and target

In [3]:
features = wine_df.drop('class', axis = 1)
target = wine_df["class"]

# Split test and train sets

In [4]:
from sklearn.model_selection import train_test_split
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.25, random_state=10)

# Training
## Note: In this homework, all of the classification methods (logistic regression, decision tree, random forest, SVM, KNN and Naive Bayes) will be used.

## Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression
lgr_clf = LogisticRegression(multi_class='multinomial', solver='lbfgs', C=10)
lgr_clf.fit(features_train, target_train)

C:\Users\Radin\Desktop\ML-Basic\ML_Basic_venv\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=10, multi_class='multinomial')

## Decision Tree

In [7]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(features_train, target_train)

DecisionTreeClassifier(max_depth=2)

## Random Forest

In [8]:
from sklearn.ensemble import RandomForestClassifier
rnd_clf = RandomForestClassifier()
rnd_clf.fit(features_train, target_train)

RandomForestClassifier()

## SVM

In [65]:
from sklearn.svm import SVC
svm_clf = SVC(probability=True)
svm_clf.fit(features_train, target_train)

SVC(probability=True)

## KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(features_train, target_train)

KNeighborsClassifier(n_neighbors=3)

## Naive Bayes

In [11]:
from sklearn.naive_bayes import GaussianNB
gnb_clf = GaussianNB()
gnb_clf.fit(features_train, target_train)

GaussianNB()

# Evaluation

 ### Use score method to get accuracy of model

## Logistic Regression

In [14]:
score_train_lgr = lgr_clf.score(features_train, target_train)
print('The accuracy of lgr is:', score_train_lgr)

The accuracy of lgr is: 0.9774436090225563


# Decision Tree

In [15]:
score_train_tree = tree_clf.score(features_train, target_train)
print('The accuracy of tree is:', score_train_tree)

The accuracy of tree is: 0.9774436090225563


## Random Forest

In [17]:
score_train_rnd = rnd_clf.score(features_train, target_train)
print('The accuracy of rnd is:', score_train_rnd)

The accuracy of rnd is: 1.0


## SVM

In [66]:
score_train_svm = svm_clf.score(features_train, target_train)
print('The accuracy of svm is:', score_train_svm)

The accuracy of svm is: 0.7368421052631579


## KNN

In [19]:
score_train_knn = knn_clf.score(features_train, target_train)
print('The accuracy of knn is:', score_train_knn)

The accuracy of knn is: 0.8646616541353384


## Naive Bayes

In [20]:
score_train_gnb = gnb_clf.score(features_train, target_train)
print('The accuracy of gnb is:', score_train_gnb)

The accuracy of gnb is: 0.9849624060150376


# Test the model

 ### Use score method to get accuracy of model by test data

## Logistic Regression

In [21]:
score_test_lgr = lgr_clf.score(features_test, target_test)
print('The accuracy of lgr is:', score_test_lgr)

The accuracy of lgr is: 0.8444444444444444


## Decision Tree

In [22]:
score_test_tree = tree_clf.score(features_test, target_test)
print('The accuracy of tree is:', score_test_tree)

The accuracy of tree is: 0.8


## Random Forest

In [23]:
score_test_rnd = rnd_clf.score(features_test, target_test)
print('The accuracy of rnd is:', score_test_rnd)

The accuracy of rnd is: 0.9555555555555556


## SVM

In [67]:
score_test_svm = svm_clf.score(features_test, target_test)
print('The accuracy of svm is:', score_test_svm)

The accuracy of svm is: 0.6666666666666666


## KNN

In [25]:
score_test_knn = knn_clf.score(features_test, target_test)
print('The accuracy of knn is:', score_test_knn)

The accuracy of knn is: 0.6666666666666666


## Naive Bayes

In [26]:
score_test_gnb = gnb_clf.score(features_test, target_test)
print('The accuracy of gnb is:', score_test_gnb)

The accuracy of gnb is: 0.8888888888888888


# Prediction of models

## Logistic Regression

In [27]:
predicted_test_class_lgr = lgr_clf.predict(features_test)

## Decision Tree

In [28]:
predicted_test_class_tree = tree_clf.predict(features_test)

## Random Forest

In [29]:
predicted_test_class_rnd = rnd_clf.predict(features_test)

## SVM

In [68]:
predicted_test_class_svm = svm_clf.predict(features_test)

## KNN

In [31]:
predicted_test_class_knn = knn_clf.predict(features_test)

## Naive Bayes

predicted_test_class_gnb = gnb_clf.predict(features_test)

# Confusion Matrix, Classification Report and ROC AUC Score

### Note: Because of the dataset has multi calsses, roc curve can not plot, then, it will be used the roc auc score with OVO strategy.

In [48]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score

## Logistic Regression

In [59]:
print('The confusion matrix of lgr: \n', confusion_matrix(target_test, predicted_test_class_lgr), '\n')
print('The classification report of lgr: \n', classification_report(target_test, predicted_test_class_lgr))

y_pred_proba_lgr  = lgr_clf.predict_proba(features_test)
print ('roc auc score of lgr: \n', roc_auc_score(target_test, y_pred_proba_lgr, multi_class='ovo'))

The confusion matrix of lgr: 
 [[12  1  0]
 [ 4 17  2]
 [ 0  0  9]] 

The classification report of lgr: 
               precision    recall  f1-score   support

           1       0.75      0.92      0.83        13
           2       0.94      0.74      0.83        23
           3       0.82      1.00      0.90         9

    accuracy                           0.84        45
   macro avg       0.84      0.89      0.85        45
weighted avg       0.86      0.84      0.84        45

roc auc score of lgr: 
 0.9772079772079773


## Decision Tree

In [60]:
print('The confusion matrix of tree: \n', confusion_matrix(target_test, predicted_test_class_tree), '\n')
print('The classification report of tree: \n', classification_report(target_test, predicted_test_class_tree))

y_pred_proba_tree  = tree_clf.predict_proba(features_test)
print ('roc auc score of tree: \n', roc_auc_score(target_test, y_pred_proba_tree, multi_class='ovo'))

The confusion matrix of tree: 
 [[12  1  0]
 [ 5 16  2]
 [ 0  1  8]] 

The classification report of tree: 
               precision    recall  f1-score   support

           1       0.71      0.92      0.80        13
           2       0.89      0.70      0.78        23
           3       0.80      0.89      0.84         9

    accuracy                           0.80        45
   macro avg       0.80      0.84      0.81        45
weighted avg       0.82      0.80      0.80        45

roc auc score of tree: 
 0.8925740121392295


## Random Forest

In [61]:
print('The confusion matrix of rnd: \n', confusion_matrix(target_test, predicted_test_class_rnd), '\n')
print('The classification report of rnd: \n', classification_report(target_test, predicted_test_class_rnd))

y_pred_proba_rnd  = rnd_clf.predict_proba(features_test)
print ('roc auc score of rnd: \n', roc_auc_score(target_test, y_pred_proba_rnd, multi_class='ovo'))

The confusion matrix of rnd: 
 [[13  0  0]
 [ 0 21  2]
 [ 0  0  9]] 

The classification report of rnd: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        13
           2       1.00      0.91      0.95        23
           3       0.82      1.00      0.90         9

    accuracy                           0.96        45
   macro avg       0.94      0.97      0.95        45
weighted avg       0.96      0.96      0.96        45

roc auc score of rnd: 
 0.9967484206614641


## SVM

In [69]:
print('The confusion matrix of svm: \n', confusion_matrix(target_test, predicted_test_class_svm), '\n')
print('The classification report of svm: \n', classification_report(target_test, predicted_test_class_svm))

y_pred_proba_svm  = svm_clf.predict_proba(features_test)
print ('roc auc score of svm: \n', roc_auc_score(target_test, y_pred_proba_svm, multi_class='ovo'))

The confusion matrix of svm: 
 [[ 8  0  5]
 [ 2 16  5]
 [ 0  3  6]] 

The classification report of svm: 
               precision    recall  f1-score   support

           1       0.80      0.62      0.70        13
           2       0.84      0.70      0.76        23
           3       0.38      0.67      0.48         9

    accuracy                           0.67        45
   macro avg       0.67      0.66      0.65        45
weighted avg       0.74      0.67      0.69        45

roc auc score of svm: 
 0.8622569057351667


## KNN

In [63]:
print('The confusion matrix of knn: \n', confusion_matrix(target_test, predicted_test_class_knn), '\n')
print('The classification report of knn: \n', classification_report(target_test, predicted_test_class_knn))

y_pred_proba_knn  = knn_clf.predict_proba(features_test)
print ('roc auc score of knn: \n', roc_auc_score(target_test, y_pred_proba_knn, multi_class='ovo'))

The confusion matrix of knn: 
 [[ 9  0  4]
 [ 4 15  4]
 [ 1  2  6]] 

The classification report of knn: 
               precision    recall  f1-score   support

           1       0.64      0.69      0.67        13
           2       0.88      0.65      0.75        23
           3       0.43      0.67      0.52         9

    accuracy                           0.67        45
   macro avg       0.65      0.67      0.65        45
weighted avg       0.72      0.67      0.68        45

roc auc score of knn: 
 0.8322185061315497


## Naive Bayes

In [64]:
print('The confusion matrix of gnb: \n', confusion_matrix(target_test, predicted_test_class_gnb), '\n')
print('The classification report of gn: \n', classification_report(target_test, predicted_test_class_gnb))

y_pred_proba_gnb  = gnb_clf.predict_proba(features_test)
print ('roc auc score of gnb: \n', roc_auc_score(target_test, y_pred_proba_gnb, multi_class='ovo'))

The confusion matrix of gnb: 
 [[13  0  0]
 [ 2 18  3]
 [ 0  0  9]] 

The classification report of gn: 
               precision    recall  f1-score   support

           1       0.87      1.00      0.93        13
           2       1.00      0.78      0.88        23
           3       0.75      1.00      0.86         9

    accuracy                           0.89        45
   macro avg       0.87      0.93      0.89        45
weighted avg       0.91      0.89      0.89        45

roc auc score of gnb: 
 0.9972129319955406


# Comparision of the models:

## In the evaluation, the worst model is KNN.

## In the test models, the worst models are SVM and NKN.

## The maximum of the ROC AUC score are related to the Random Forest and Naive Baes.

## As a result, the best models are Naive Bayes, Random Forest and Logistic regression.