In [67]:
import numpy as np
import requests

# تمامی سوالات با نامپای حل شود و لیست ها به
# numpy array

# تبدیل شود
 نامپای اری = numpy array

 اری = array

۱-
اعداد فرد را با -۱ جایگزین کنید

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
n_odd = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
n_odd[n_odd % 2 !=0] = -1
n_odd

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

۲- خروجی کد بالا را به شکل زیر تغییر دهید

In [12]:
n_odd.reshape(2,5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

[1,2,3,2,3,4,3,4,5,6]

[7,2,10,2,7,4,9,4,9,8]

۳- مشخص کنید بین دو لیست گفته شده کدام اعضا و در چه ایندکسی اشتراک دارند

In [8]:
l1, l2=[1,2,3,2,3,4,3,4,5,6],[7,2,10,2,7,4,9,4,9,8]
l1, l2 = np.array(l1), np.array(l2)

shared_elements = np.intersect1d(l1,l2,return_indices=True)
shared_elements

(array([2, 4]), array([1, 5]), array([1, 5]))

In [10]:
np.where(np.isin(l1, shared_elements))[0]

array([0, 1, 3, 5, 7, 8])

In [11]:
 np.where(np.isin(l2, shared_elements))[0]

array([1, 3, 5, 7])

array([ 0,  1,  2, ..., 12, 13, 14]

۴- برای حذف سه نقطه به هنگام پرینت چه راهی پیشنهاد می دهید

و با چه روشی میتوان چک کرد مقدار خالی وجود دارد یا خیر


In [10]:
np.set_printoptions(threshold=np.inf)
print('S1:',x)

np.set_printoptions(threshold=5)
x=np.array([ 0, 1, 2,2,153,3,4,5,6,12,4356,123,123,123, 12, 13, 14])
print('S2:',x.tolist())



S1: [   0    1    2    2  153    3    4    5    6   12 4356  123  123  123
   12   13   14]
S2: [0, 1, 2, 2, 153, 3, 4, 5, 6, 12, 4356, 123, 123, 123, 12, 13, 14]


۵- مقادیر یکتای لیست زیر چقدر است و از هر کدام چند تا در لیست وجود دارد

[1,2,3,2,3,4,3,4,5,6]

In [14]:
l5=np.array([1,2,3,2,3,4,3,4,5,6])
# np.unique(l5,return_counts=True)

unique_values, counts = np.unique(l5, return_counts=True)

for value, count in zip(unique_values, counts):
    print(f"K: {value}, Count: {count}")

K: 1, Count: 1
K: 2, Count: 2
K: 3, Count: 3
K: 4, Count: 2
K: 5, Count: 1
K: 6, Count: 1


۶- یک array

 رندوم ۳۰ عضوی بین اعداد ۱ تا ۵۰ بسازید و اعدادی که کوچکتر از ۱۰ هستند را به ۱۰ و اعدادی که از ۳۰ بزرگتر هستند را به ۳۰ تغییر دهید

In [47]:
arr = np.random.randint(1, 51, size=30)
arr[arr < 10] = 10  
arr[arr > 30] = 30  

print(arr)

[10 10 30 ... 10 30 29]


[33.14924709 30.39618519 25.54217583 19.57381963  4.24468725 35.04802683
  7.46221009  8.7607952  48.46878651 45.28799358 27.07073741 11.04564957
 19.78331448 45.29088422  7.17456182 26.43073495  5.63140353 18.6468186
 15.12981261 35.0725932  42.21729431 17.06519106 10.75266421 15.80499943
 31.49733997 32.77095484 31.90320938 29.84397576 19.11062236  9.63998387]
[30.         30.         25.54217583 19.57381963 10.         30.
 10.         10.         30.         30.         27.07073741 11.04564957
 19.78331448 30.         10.         26.43073495 10.         18.6468186
 15.12981261 30.         30.         17.06519106 10.75266421 15.80499943
 30.         30.         30.         29.84397576 19.11062236 10.        ]


۷-  array یک

سه بعدی ساخته و در انتها آن را یک بعدی کنید

In [52]:
array_3d = np.arange(27).reshape(3,3,3)
array_3d.flatten()


array([ 0,  1,  2, ..., 24, 25, 26])

array_of_arrays:  [array([0, 1, 2]) array([2, 3, 4, 5, 6]) array([7, 8, 9])]
array_of_arrays:  (3,)
[0 1 2 2 3 4 5 6 7 8 9]


<ipython-input-66-a491e9c35e8a>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3])


۸- بزرگترین عضو در هر ردیف و سپس بزرگترین عضو در هر ستون بیابید

In [59]:
import numpy as np

np.random.seed(100)
a = np.random.randint(1,10, [8,4])
# print(a)

max_in_each_row = np.max(a, axis=1)
print(f"{max_in_each_row=} ")


max_in_each_col = np.max(a, axis=0)
print(f"{max_in_each_col=} ")

max_in_each_row=array([9, 8, 6, ..., 6, 8, 8]) 
max_in_each_col=array([9, 9, 9, 8]) 


In [ ]:
np.

۹- نامپای اری را بسازید که بین دو تاریخ '2022-02-01' و '2022-02-25'
به صورت یک روز در میان باشد

حالا روزهای جا افتاده در اری بالا را به آن اضافه کنید


In [66]:
import numpy as np

start_date = np.datetime64('2022-02-01')
end_date = np.datetime64('2022-02-25')

dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')

print(dates)
dates

['2022-02-01' '2022-02-02' '2022-02-03' ... '2022-02-23' '2022-02-24'
 '2022-02-25']


array(['2022-02-01', '2022-02-02', '2022-02-03', ..., '2022-02-23',
       '2022-02-24', '2022-02-25'], dtype='datetime64[D]')

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']


array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

۱۰- عکس زیر را با کتابخانه

requests

گرفته و سپس با استفاده از کتابخانه

BytesIO

آن را باز کرده و به سایز ۲۵۰ در ۲۵۰ تغییر داده و در نامپای اری ذخیره کنید


In [79]:
url = 'https://via.placeholder.com/150/FF0000/FFFFFF?Text=yttags.com'  # Replace with the actual image URL
response = requests.get(url)

In [92]:
import requests
from PIL import Image
import numpy as np
from io import BytesIO
# Image
# Get the image using requests library
url = 'https://via.placeholder.com/150/FF0000/FFFFFF?Text=yttags.com'  # Replace with the actual image URL
response = requests.get(url)
image_data = response.content

# Open the image and resize it to 250x250
image = Image.open(BytesIO(image_data))
print(np.array(image).shape)
resized_image = image.resize((250, 250))

# Convert the resized image to a NumPy array
image_array = np.array(resized_image)
image.save(fp='test_image.jpg')
# Print the shape of the image array
print('------------------------------')
print(image_array.shape)

(150, 150, 3)
------------------------------
(250, 250, 3)


array([[[100, 103, 112],
        [ 98, 101, 110],
        [ 97, 100, 109],
        ...,
        [120, 119, 124],
        [120, 119, 124],
        [114, 113, 118]],

       [[107, 110, 119],
        [106, 109, 118],
        [102, 105, 114],
        ...,
        [116, 115, 121],
        [117, 116, 121],
        [116, 115, 120]],

       [[108, 111, 120],
        [108, 111, 120],
        [101, 104, 113],
        ...,
        [106, 105, 111],
        [112, 111, 116],
        [116, 115, 120]],

       ...,

       [[ 64,  62,  73],
        [ 66,  64,  75],
        [ 67,  65,  76],
        ...,
        [240, 241, 238],
        [237, 238, 233],
        [237, 238, 233]],

       [[ 65,  63,  74],
        [ 66,  64,  75],
        [ 70,  68,  79],
        ...,
        [241, 241, 239],
        [240, 241, 236],
        [240, 241, 236]],

       [[ 73,  71,  82],
        [ 70,  68,  79],
        [ 72,  70,  81],
        ...,
        [239, 239, 238],
        [240, 240, 237],
        [240, 241, 236]]

# linux
1-برای تنظیمات گراب بهتر است کدوم فولدر تغییر داده شود

در این مسیر میتوان فایل های گراب را تغییر داد 
/etc/defult/grub

2- شما برنامه ای را برای پیش بینی قیمت کالا نوشته اید این برمامه برای ران شدن احتیاج به خواندن ورودی به عنوان کانفیگ دارد کانفیگ های برنامه بهتر است چگونه و در کجا اعمال شوند

3-به نظر شما نود پرینتر یا هر سخت افزار در کدام فولدر ذخیره میشود

/dev

4-چیست bios کار

نرم‌افزاری است که مسئول بوت کردن و آماده سازی  اولیه  اجزای سخت‌افزاری سیستم قبل از کنترل سیستم عامل می‌باشد. این نرم‌افزار عملیات ورودی/خروجی در سطح پایین و مقداردهی اولیه سخت‌افزار را فراهم می‌کند.
و پس از آن کنترل سیستم را به سیستم عامل میدهد. یک جورایی عملا سیستم روشن میکنه و سیستم عامل رو میاره بالا و یسری اطلاعات به سیستم عامل میده تا بتونه کارش رو انجام بده

5- منظور از ~ چیست

ادرس home یوز را نشان میدهد
cd /home/<username>/ === cd . 
